languageCode = "ar"
languageName = "Arabic"
languageDirection = "rtl"
weight = 1

title = "أبو هاشم"
copyright = "&copy; 2025   "

[params]
  dateFormat = "2 يناير 2006"

  # mainSections = ["posts"]
  description = "موضوع قوي وخفيف الوزن لـ Hugo مبني باستخدام Tailwind CSS."

[params.author]
  name = "محمد عبد البديع أبو هاشم"
  image = "img/author.jpg"
  headline = " موضوعك !"
  bio = "هذا مثال على السيرة الذاتية للمؤلف ، وعلى الرغم من وجود صورة لمخزون  هنا ، إلا أن هذه المقالة تم إنشاؤها بالفعل بواسطة إنسان. :dog:"
  links = [
    # { x-twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    # { linkedin = "https://linkedin.com/" },
    # { youtube = "https://youtube.com/" },
    { telegram = "https://t.me/username" },
  ]
